### ISSUE TITLE
关于软件改进的小建议

### ISSUE THREAD

**Issue by liwenbus** [wjbgis/Sedentary-reminder#3]
你好，我非常喜欢你的小工具，这是我用过最小最简洁的久坐提醒工具，真的非常感谢你设计这么好的软件。不过，我有以下建议：
1、时间设置可以存储在一个setting.ini吗，每次打开都要设置时间不方便。
2、不知道为何，鼠标移动那个绿色窗口时会乱闪，希望改进一下

非常感谢

**Comment by wjbgis** [comment]
非常感谢您的建议，最近事情太多了，一直没关注这个库。抽时间我改下哈。

**Comment by wjbgis** [comment]
> 你好，我非常喜欢你的小工具，这是我用过最小最简洁的久坐提醒工具，真的非常感谢你设计这么好的软件。不过，我有以下建议：
> 1、时间设置可以存储在一个setting.ini吗，每次打开都要设置时间不方便。
> 2、不知道为何，鼠标移动那个绿色窗口时会乱闪，希望改进一下
> 
> 非常感谢

非常感谢您的建议，临毕业前无聊做的小工具，最近事情太多了一直没关注这个库，刚看到issue，实在抱歉哈。抽时间我修复下。

**Comment by liwenbus** [comment]
好的好的，非常感谢
